package service

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"dengdeng/internal/config"
	"dengdeng/internal/model"

	"gorm.io/gorm"
)

var ErrBackupUnsupported = errors.New("database snapshots are currently supported for SQLite deployments only")

// BackupService creates consistent SQLite snapshots using VACUUM INTO rather
// than copying a live WAL database file. It deliberately never offers restore
// from the web: restoring is an operator-run maintenance action that requires
// stopping the service and verifying the selected snapshot.
type BackupService struct {
	db  *gorm.DB
	cfg *config.Config
	mu  sync.Mutex
}

func NewBackupService(db *gorm.DB, cfg *config.Config) *BackupService {
	return &BackupService{db: db, cfg: cfg}
}

func (s *BackupService) directory() (string, error) {
	if s == nil || s.cfg == nil {
		return "", fmt.Errorf("backup configuration unavailable")
	}
	dir := strings.TrimSpace(s.cfg.Backup.Directory)
	if dir == "" {
		if s.cfg.Database.Driver != "" && s.cfg.Database.Driver != "sqlite" {
			return "", ErrBackupUnsupported
		}
		path, err := filepath.Abs(s.cfg.Database.Path)
		if err != nil {
			return "", err
		}
		dir = filepath.Join(filepath.Dir(path), "backups")
	}
	return filepath.Abs(dir)
}

func (s *BackupService) List(limit int) ([]model.BackupRecord, error) {
	if s == nil || s.db == nil {
		return nil, fmt.Errorf("backup store unavailable")
	}
	if limit < 1 {
		limit = 1
	}
	if limit > 200 {
		limit = 200
	}
	var items []model.BackupRecord
	err := s.db.Order("id DESC").Limit(limit).Find(&items).Error
	return items, err
}

func (s *BackupService) Create(createdBy string) (model.BackupRecord, error) {
	if s == nil || s.db == nil || s.cfg == nil {
		return model.BackupRecord{}, fmt.Errorf("backup service unavailable")
	}
	if s.cfg.Database.Driver != "" && s.cfg.Database.Driver != "sqlite" {
		return model.BackupRecord{}, ErrBackupUnsupported
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	dir, err := s.directory()
	if err != nil {
		return model.BackupRecord{}, err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return model.BackupRecord{}, fmt.Errorf("create backup directory: %w", err)
	}
	filename := "dengdeng-" + time.Now().UTC().Format("20060102T150405.000000000Z") + ".sqlite"
	record := model.BackupRecord{Filename: filename, Status: "creating", CreatedBy: strings.TrimSpace(createdBy)}
	if err := s.db.Create(&record).Error; err != nil {
		return model.BackupRecord{}, err
	}
	path := filepath.Join(dir, filename)
	// VACUUM INTO does not accept the filename as a normal SELECT parameter.
	// It is generated by this method and additionally SQL-quoted here.
	sqlPath := strings.ReplaceAll(path, "'", "''")
	if err := s.db.Exec("VACUUM INTO '" + sqlPath + "'").Error; err != nil {
		_ = os.Remove(path)
		_ = s.db.Model(&record).Updates(map[string]any{"status": "failed", "error": backupError(err.Error())}).Error
		record.Status, record.Error = "failed", backupError(err.Error())
		return record, fmt.Errorf("create sqlite snapshot: %w", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		return record, fmt.Errorf("inspect sqlite snapshot: %w", err)
	}
	if err := os.Chmod(path, 0o600); err != nil {
		return record, fmt.Errorf("protect sqlite snapshot: %w", err)
	}
	now := time.Now().UTC()
	if err := s.db.Model(&record).Updates(map[string]any{"status": "ready", "size_bytes": info.Size(), "completed_at": now, "error": ""}).Error; err != nil {
		return record, err
	}
	record.Status, record.SizeBytes, record.CompletedAt, record.Error = "ready", info.Size(), &now, ""
	return record, nil
}

func (s *BackupService) SnapshotPath(id int64) (model.BackupRecord, string, error) {
	if s == nil || s.db == nil || id <= 0 {
		return model.BackupRecord{}, "", fmt.Errorf("invalid backup")
	}
	var record model.BackupRecord
	if err := s.db.First(&record, id).Error; err != nil {
		return record, "", err
	}
	if record.Status != "ready" {
		return record, "", fmt.Errorf("backup is not ready")
	}
	dir, err := s.directory()
	if err != nil {
		return record, "", err
	}
	filename := filepath.Base(record.Filename)
	if filename != record.Filename || filename == "." {
		return record, "", fmt.Errorf("invalid backup record")
	}
	path := filepath.Join(dir, filename)
	if _, err := os.Stat(path); err != nil {
		return record, "", err
	}
	return record, path, nil
}

func (s *BackupService) Delete(id int64) error {
	if s == nil || s.db == nil || id <= 0 {
		return fmt.Errorf("invalid backup")
	}
	var record model.BackupRecord
	if err := s.db.First(&record, id).Error; err != nil {
		return err
	}
	if record.Status == "ready" {
		_, path, err := s.SnapshotPath(id)
		if err != nil {
			return err
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return s.db.Delete(&record).Error
}

func backupError(value string) string {
	if len(value) > 480 {
		return value[:480]
	}
	return value
}
