package service

type creationSkillEnglish struct {
	name        string
	description string
	content     string
}

func applyCreationSkillEnglish(skills []CreationLibraryEntry) {
	translations := map[string]creationSkillEnglish{
		"code-reviewer":        {"Code Review", "Find defects, regressions, and security boundary issues", "Read repository rules, the complete change, callers, data contracts, and related tests. Trace changed entries through persistence, external side effects, and recovery, checking correctness, authorization, concurrency, compatibility, and resource lifetime. Every finding must include severity, exact location, trigger, impact, evidence, the smallest valid fix, and regression verification. Separate verified defects, hypotheses, and preferences, and state uncovered scope when no issue is found."},
		"debugger":             {"Troubleshooting", "Locate root causes from symptoms and logs", "Fix the environment, version, preconditions, shortest reproduction, expected result, and actual result, then build a timeline from entry to failure. Separate facts, competing hypotheses, and unknowns, follow the data to the first divergence, and test one variable at a time. Fix the owning boundary, remove temporary fallbacks, and retest the original path, adjacent boundaries, and recovery. When evidence is insufficient, give only the next observation that will narrow the fault."},
		"backend-engineer":     {"Backend Engineering", "Design APIs, data flows, and concurrent services", "Derive the input, identity, state preconditions, output, side effects, failures, and retry contract from callers, models, migrations, configuration, and tests. Give business rules and state transitions one owner, keep critical data and billing writes atomic, and make external effects idempotent, time-bounded, and reconcilable. Propagate cancellation, release resources, preserve error causes behind stable API mappings, and test the relevant success, failure, concurrency, or upgrade partitions."},
		"frontend-engineer":    {"Frontend Engineering", "Build usable, responsive, accessible interfaces", "Inspect the existing framework, routing, state, API types, tokens, and components, then structure the task from the narrowest supported width. Cover loading, empty, error, retry, disabled, cancellation, keyboard, touch, long content, and dark mode. Prevent unintended horizontal overflow, clipping, and color-only status. Verify critical interactions, console, network, desktop, and mobile in the real rendered page."},
		"api-designer":         {"API Design", "Define request contracts and compatibility boundaries", "Start from real client tasks and the current protocol to define callers, identity, resource ownership, and operations. Specify methods, paths, headers, parameters, bodies, success and empty results, stable error codes, pagination and ordering, rate limits, caching, idempotency, and stream termination. Provide executable positive, boundary, and failure examples. Check old clients, defaults, unknown fields, and enum growth, and document breaking changes, migration periods, and verifiable compatibility."},
		"data-analyst":         {"Data Analysis", "Analyze metrics, anomalies, and reproducible findings", "Confirm the question, decision, source, grain, key, fields, units, time range, time zone, sample, and gaps. Check missing values, duplicates, ranges, cardinality, and latency before defining numerator, denominator, deduplication, window, and rounding. Begin with descriptive and segmented comparisons, investigate definition and structural changes before explaining anomalies, and deliver reproducible queries or scripts with sample size, uncertainty, and limitations. Separate facts, correlation, causality, and hypotheses."},
		"research-synthesizer": {"Research Synthesis", "Compare sources, evidence, and disagreements", "Turn the request into a precise question with region, date, version, and subject. Prefer official documentation, laws, papers, datasets, repositories, and direct announcements. Record each source's date, scope, supported claim, and limits, and cross-check important facts. Resolve conflicts by checking versions, definitions, samples, and time. Synthesize by question rather than source, cite claims in place, and separate sourced facts, inferences, disagreements, and unknowns."},
		"technical-writer":     {"Technical Writing", "Write accurate documentation and release information", "Define the reader, task, surface, and required questions, then derive facts from current source, configuration, APIs, commands, tests, and runtime evidence. Organize content in execution order with prerequisites, inputs, outputs, side effects, limits, recovery, and runnable examples. Verify names, versions, commands, links, and fields. Remove repetition, process narration, and unsupported claims, explain impact and recovery before destructive actions, and mark unverified content."},
		"translator":           {"Professional Translation", "Preserve terminology, tone, and structure", "Confirm source language, target locale, audience, text type, tone, and glossary. Identify code, keys, commands, URLs, placeholders, brands, numbers, and legal qualifiers that must not change. Translate complete semantic units naturally while preserving headings, lists, tables, Markdown, HTML, and resource structure. Check negation, conditions, units, dates, links, terminology, and placeholders. Do not add or remove facts, and surface only ambiguities that affect the result."},
		"product-planner":      {"Product Planning", "Turn requirements into boundaries and acceptance criteria", "Establish the problem from user statements, usage data, support evidence, and the current product. Define target user, trigger, current alternative, desired outcome, and success metric. State scope, non-goals, dependencies, and unchanged behavior, then specify main paths, states, permissions, data, repetition, failures, and recovery. Convert requirements into observable acceptance criteria covering normal, boundary, failure, and role differences, and prioritize by impact, evidence, cost, risk, and dependency."},
		"visual-director":      {"Visual Direction", "Control composition, lighting, color, and material", "Define the medium, size, aspect ratio, audience, subject, required elements, and exclusions, then state the first visual focal point in one sentence. Specify framing, viewpoint, lens character, depth, negative space, and eye path, followed by key-light direction, softness, temperature, a restrained palette, and material response. Lock character, product, camera, and color anchors across a series, then verify structure, text, edges, reflections, shadows, and background interference."},
		"layout-designer":      {"Layout Design", "Create readable grids and information hierarchy", "Collect final copy, imagery, marks, dimensions, viewing distance, output format, and safe areas. Mark primary, secondary, and supporting information and remove repetition before defining columns, margins, baselines, alignment, and a limited spacing scale. Set typography roles, size, leading, weight, and multilingual rules. Reflow long titles, localization, narrow widths, and export crops rather than shrinking everything, keeping all required text legible and decoration clear of content."},
		"storyboard":           {"Storyboarding", "Plan shots, movement, and continuity", "Define the film's purpose, platform, aspect ratio, total duration, audience, and core message, then split the script into beats with one action, idea, or emotional change each. For every shot specify purpose, framing, camera, lens, composition, subject and environment action, movement, duration, sound, and transition. Maintain a continuity table for character, wardrobe, product, props, screen direction, and light, and check total timing, axis jumps, action matches, redundant shots, and generation difficulty."},
		"audio-director":       {"Audio Direction", "Direct voice, pacing, and sound layers", "Define purpose, platform, target length, audience, locale, playback environment, and format, and document pronunciations for names, brands, acronyms, numbers, and terms. Specify timbre, distance, tone, pace, pauses, emphasis, and emotional arc, then place voice, ambience, effects, and music over time with clear loudness hierarchy. Verify intelligibility, clipping, noise, sibilance, edits, mono compatibility, loudness, and delivery specifications."},

		"frontend-app-builder":     {"Frontend App Builder", "Build complete interfaces from structure to verification", "Confirm the goal, information architecture, design constraints, and key states before building reusable layouts and components. Verify the real page, including responsive and failure states."},
		"frontend-testing":         {"Frontend Testing and Debugging", "Reproduce and diagnose interface failures", "Record reproducible steps, expected behavior, and actual behavior. Inspect console, network, DOM, and styles, change one variable at a time, and retest boundary and mobile states."},
		"data-visualization":       {"Data Visualization", "Choose charts that accurately express data relationships", "Define the audience, question, metric, and comparison before choosing visual encodings. Make axes, units, time range, uncertainty, interaction, and acceptance criteria explicit."},
		"accessible-visualization": {"Accessible Visualization", "Make charts usable with keyboards and assistive technology", "Provide a meaningful title, summary, and data-table or text equivalent. Preserve keyboard access, visible focus, contrast, and non-color encodings for every state."},
		"threat-modeling":          {"Threat Modeling", "Identify risks from assets, boundaries, and attack paths", "Map the system, assets, actors, data flows, and trust boundaries. Record relevant threats with prerequisites, path, impact, controls, testable mitigations, and residual risk."},
		"security-diff-review":     {"Security Diff Review", "Assess the security impact of code changes", "Inspect the change and its callers for authentication, input handling, credentials, data access, command execution, and dependency changes. Support every finding with a reachable path and evidence."},
		"skill-authoring":          {"Skill Authoring", "Package a workflow as a reusable skill", "Define triggers, inputs, outputs, available tools, completion criteria, executable steps, failure recovery, and verification. Exclude one-off project details that are not part of the reusable contract."},
		"ios-debugging":            {"iOS Debugging", "Diagnose build, runtime, and interface failures", "Confirm Xcode, SDK, deployment target, scheme, and device environment. Separate compile, link, launch, network, concurrency, and layout failures, then verify supported OS paths."},
		"document-coauthoring":     {"Document Coauthoring", "Create reviewable documents through structured iteration", "Confirm the reader, purpose, length, and required facts, then agree on an outline. Draft section by section and review repetition, evidence, terminology, and action items."},
		"mcp-server-builder":       {"MCP Server Builder", "Design stable tools and resource interfaces", "Map user tasks to a small set of high-value tools or resources. Define schemas, permissions, pagination, errors, and idempotency, then provide runnable positive and negative examples."},
		"internal-communications":  {"Internal Communications", "Write status updates, announcements, and decisions", "Identify the audience and required action. State the current facts, change, impact, owner, timing, risks, and unknowns without promotional language or vague commitments."},
		"brand-guidelines":         {"Brand Guidelines", "Apply an existing brand consistently", "Extract rules for logo use, color, typography, spacing, imagery, and voice. Make only the minimum assumptions where guidance is missing and identify assets that cannot be verified."},
		"algorithmic-art":          {"Algorithmic Art", "Create parameterized and reproducible generative visuals", "Define the visual system, seed, canvas, palette, and parameter ranges before describing the generation rules. Keep hierarchy and export requirements stable across variations."},
		"canvas-design":            {"Canvas Design", "Compose posters and static canvases", "Set the grid, focal point, text hierarchy, spacing, and bleed from the target dimensions and viewing distance. Keep required text legible and integrate imagery and type into one composition."},
		"webapp-testing":           {"Web Application Acceptance", "Test real user paths and failure states", "Turn requirements into executable paths covering authentication, permissions, forms, loading, empty, error, and responsive states. Record evidence and run focused regression after fixes."},
		"theme-factory":            {"Theme System Design", "Build complete themes with reusable design tokens", "Define surfaces, text, accents, states, typography, spacing, radius, shadow, charts, interactions, light and dark modes, and mobile behavior. A theme must change more than its primary color."},
		"react-performance":        {"React Performance", "Diagnose React and Next.js bottlenecks by impact", "Use measurements to locate request waterfalls, bundle cost, server latency, repeated rendering, and client data fetching. Fix the highest-impact issue first and compare before-and-after metrics."},
		"web-design-audit":         {"Web Design Audit", "Review usability, accessibility, and responsive behavior", "Inspect semantics, keyboard access, focus, forms, motion, typography, images, navigation, dark mode, touch, and internationalization. Report only findings tied to a concrete interface or code path."},
		"react-native-engineering": {"React Native Engineering", "Build performant, platform-appropriate mobile experiences", "Confirm platforms, navigation, state, and data boundaries. Validate lists, images, animation, bridges, accessibility, keyboard, safe areas, and iOS and Android interaction differences."},
		"writing-guidelines":       {"Product Copy Editing", "Make interface and documentation copy direct and actionable", "Edit for the reader's task, structure, terminology, examples, numbers, and code. Prefer direct actions, remove filler, and make errors state the failure and next step."},

		"brainstorming-workflow":         {"Solution Exploration", "Clarify the problem and compare distinct approaches", "Confirm the problem from current evidence, then propose a small set of meaningfully different options. Compare user impact, complexity, risk, and validation cost before making a concrete decision."},
		"systematic-debugging":           {"Systematic Debugging", "Narrow failures with evidence", "Reproduce the failure and collect evidence close to the fault. Follow the data and call path to the first divergence, test hypotheses individually, and verify the original and adjacent cases."},
		"test-driven-development":        {"Test-Driven Development", "Use a failing test to preserve the required behavior", "Write the smallest failing test that exercises real logic, implement the minimum behavior that makes it pass, then refactor and run related tests. Avoid tests of static definitions or mocks alone."},
		"verification-before-completion": {"Verification Before Completion", "Confirm delivery with current evidence", "Run checks that directly prove the requested behavior and verify that required artifacts exist. A failed, skipped, or stale result is not a pass; mark uncovered areas explicitly."},
		"implementation-planning":        {"Implementation Planning", "Break requirements into executable, verifiable steps", "Base the plan on current code and dependencies. Give each step a change boundary, behavior, validation, and failure handling, ordered by actual dependencies."},
		"code-review-response":           {"Code Review Response", "Validate feedback and resolve it precisely", "Check each review comment against the current contract and code. Fix valid issues at the owning source, verify the result, and explain unsupported suggestions with evidence rather than accepting them mechanically."},
		"branch-finishing":               {"Branch Finishing", "Prepare a change for merge or release", "Review the worktree, scope, tests, and generated artifacts, then remove temporary files and orphaned code created by the change. Commit, push, merge, or deploy only when authorized."},
		"performance-optimization":       {"Performance Optimization", "Find high-impact bottlenecks from measurements", "Define user-visible metrics and a baseline, then profile CPU, memory, I/O, network, or rendering. Fix the largest contributor first and record comparable before-and-after results."},
		"observability-instrumentation":  {"Observability", "Design logs, metrics, and traces that support diagnosis", "Define structured telemetry and correlation IDs around critical requests and state changes. Record actionable transitions and failures without sensitive data or normal-flow noise."},
		"security-hardening":             {"Security Hardening", "Reduce risk across real attack surfaces", "Map entry points, identities, data, dependencies, and deployment boundaries, then validate reachable risks. Prioritize configuration, permission, input, credential, and audit fixes with recovery paths."},
		"migration-engineering":          {"Migration Engineering", "Plan compatibility, validation, and rollback", "Identify old and new contracts, data shapes, callers, and irreversible steps. Design phased migration, validation, monitoring, and rollback with entry and exit criteria for every stage."},
		"ci-cd-automation":               {"CI/CD Automation", "Build repeatable delivery pipelines with rollback", "Define build inputs, caching, tests, artifacts, environments, and release permissions. Make failures diagnosable, retries safe, and deployments dependent on health checks and rollback."},
		"source-driven-development":      {"Source-Driven Development", "Implement from current source and primary documentation", "Read callers, configuration, pinned versions, and primary upstream documentation before choosing an API or design. Prefer runtime contracts and mark inferences and unverified gaps."},
		"code-simplification":            {"Code Simplification", "Reduce complexity while preserving behavior", "Confirm the external behavior and tests, then remove duplicated branches, unused abstractions, and unnecessary indirection. Prefer one clear path without weakening errors, readability, or performance."},
		"codebase-knowledge":             {"Codebase Understanding", "Map structure, boundaries, and call relationships", "Start from entry points, modules, configuration, data models, external dependencies, and tests. Trace important behavior to its owner and distinguish read evidence from naming-based guesses."},
		"architecture-blueprint":         {"Architecture Blueprint", "Describe system boundaries and data flow", "Document component responsibilities, interfaces, data flow, trust boundaries, topology, and quality attributes. Tie each decision to constraints, trade-offs, incremental implementation, and verification."},
		"bug-reproduction":               {"Bug Reproduction", "Turn an unclear failure into a stable test case", "Record environment, version, preconditions, shortest steps, expected behavior, actual behavior, and evidence. Minimize the input and report reproducibility and missing information without guessing the cause."},
		"readme-authoring":               {"README Authoring", "Write an accurate entry point for project users", "Derive purpose, requirements, installation, configuration, execution, verification, and troubleshooting from the current repository. Keep examples executable and never include real credentials."},

		"gemini-api-integration":     {"Gemini API Integration", "Build verified Gemini model calls", "Confirm models, endpoints, authentication, and request and response contracts. Implement text, multimodal, streaming, and structured output with quota, timeout, and safety handling, then test a minimal real request."},
		"realtime-multimodal":        {"Realtime Multimodal", "Design low-latency audio and video conversations", "Define session lifecycle, media formats, interruption, reconnection, and backpressure. Measure first-packet and end-to-end latency and verify recovery from denied permissions and unstable networks."},
		"rag-system-design":          {"RAG System Design", "Build retrieval pipelines that can be evaluated", "Define corpus, chunking, metadata, indexing, and permissions before retrieval, reranking, citation, and no-answer handling. Evaluate recall, grounding, and latency on representative questions."},
		"agent-evaluation":           {"Agent Evaluation", "Measure agent behavior with stable test sets", "Break the goal into task success, correctness, tool choice, cost, latency, and safety. Use fixed samples, scoring rules, failure categories, and baseline comparisons to detect regressions."},
		"prompt-lifecycle":           {"Prompt Lifecycle", "Manage prompt versions, evaluations, and releases", "Define prompt variables, output contract, supported models, and version. Link changes to evaluation results and keep rollback available while avoiding duplicated business rules."},
		"cloud-cost-review":          {"Cloud Cost Review", "Find waste from bills and utilization", "Normalize billing period, currency, tags, and allocation, then analyze cost by service, environment, and team. Validate savings against utilization and report range, risk, and a review method."},
		"cloud-reliability-review":   {"Cloud Reliability Review", "Review failure domains, recovery, and capacity", "Start from service objectives, dependencies, failure domains, capacity, and data recovery. Define detection, degradation, recovery, and game-day checks for critical failure modes."},
		"cloud-operations-review":    {"Cloud Operations Review", "Improve change management, monitoring, and incident response", "Review deployment, configuration, alerts, on-call, logs, traces, and change records. Alerts must map to actions, and runbooks must be verified through an exercise."},
		"bigquery-engineering":       {"BigQuery Data Engineering", "Design maintainable analytical datasets and queries", "Confirm schemas, partitioning, clustering, permissions, and cost limits before writing reproducible queries. Use query plans, bytes processed, and result sampling to validate efficiency and correctness."},
		"kubernetes-troubleshooting": {"Kubernetes Troubleshooting", "Diagnose workloads from state and cluster events", "Inspect desired state, pod events, logs, probes, resources, scheduling, networking, and storage in sequence. Fix only after finding the first abnormal evidence, then verify rollout and recovery."},

		"domain-modeling":           {"Domain Modeling", "Turn business rules into a coherent model", "Extract entities, value objects, states, invariants, and boundaries from user behavior and domain language. Give each rule one owner and validate the model with key scenarios and counterexamples."},
		"architecture-improvement":  {"Architecture Improvement", "Evolve coupling and responsibility boundaries incrementally", "Use call relationships and change cost to identify real friction, then define target boundaries and migration order. Keep every step runnable, reversible, and behaviorally verified."},
		"merge-conflict-resolution": {"Merge Conflict Resolution", "Restore the intended behavior of both sides", "Read both conflict sides, their callers, and tests to understand each intent. Remove markers and duplicate logic, then verify the behaviors introduced by both changes."},
		"specification-writing":     {"Technical Specification Writing", "Turn goals into implementable behavior contracts", "Document context, scope, user paths, data, interfaces, states, errors, permissions, and acceptance criteria. Separate open questions from decisions and make every requirement verifiable."},
		"ticket-breakdown":          {"Ticket Breakdown", "Split a specification into deliverable dependency steps", "Divide work by behavioral ownership and dependencies. Give each ticket a change boundary, completion state, and verification without assigning one state transition to multiple owners."},
		"rapid-prototyping":         {"Rapid Prototyping", "Validate a key assumption with the smallest usable path", "Choose one user behavior and failure condition, then build the shortest interactive path that tests them. Observe representative use before deciding which prototype code belongs in production."},
		"engineering-handoff":       {"Engineering Handoff", "Preserve accurate context for the next engineer", "Record the active objective, verified state, remaining work, changed files, decisive commands, and blockers. Include only facts needed to continue and never include sensitive values."},
		"technical-teaching":        {"Technical Teaching", "Build testable understanding for the reader", "Confirm the learner's starting point and goal, organize the explanation around one core model, and use a minimal example and counterexample. Check understanding with a question or exercise."},
		"agent-debugging":           {"Agent Debugging", "Trace divergence across prompts, tools, and state", "Correlate input, context, tool parameters, tool results, and final output. Find the first incorrect decision, distinguish model, prompt, tool-contract, and environment failures, and replay fixed cases."},
		"benchmark-design":          {"Benchmark Design", "Create repeatable and comparable performance tests", "Define workload, environment, dataset, warm-up, concurrency, and statistical method. Report distributions rather than a single fastest run and compare changes under identical conditions."},
		"evaluation-harness":        {"Evaluation Harness", "Automate cases, scoring, and regression comparison", "Define stable inputs, expected properties, scorers, and tolerances, and record model, prompt, and configuration versions. Make failures replayable and group regressions by category."},
		"machine-learning-workflow": {"Machine Learning Engineering", "Manage data, training, evaluation, and release", "Version data, features, splits, metrics, and randomness while preventing leakage. Track experiments and artifacts, then compare baseline, robustness, cost, and inference latency before release."},
		"docker-engineering":        {"Docker Engineering", "Build small, reproducible, secure images", "Pin base images and dependencies, separate build and runtime stages, use a non-root user, and minimize context. Verify image size, startup, health checks, signal handling, and runtime configuration."},
		"postgresql-engineering":    {"PostgreSQL Engineering", "Design indexes, transactions, and observable queries", "Design schemas, constraints, indexes, and transactions from access and consistency requirements. Validate with execution plans and realistic data, and account for locks and rollback in migrations."},
		"go-engineering":            {"Go Engineering", "Build clear, concurrency-safe Go services", "Follow established package boundaries and handle errors, context cancellation, and cleanup explicitly. Give concurrent state one owner and verify behavior with focused tests and race detection."},
		"python-engineering":        {"Python Engineering", "Build maintainable, testable Python systems", "Define runtime version, typing boundaries, dependencies, and entry points, and separate I/O from domain logic. Handle exceptions, context managers, and async cancellation with formatting, typing, and behavior tests."},

		"seo-audit":               {"SEO Audit", "Review crawlability, content, and page signals", "Check indexability, structure, status codes, canonicals, sitemaps, structured data, and performance before matching pages to search intent. Prioritize findings by impact and validation cost without promising rankings."},
		"content-strategy":        {"Content Strategy", "Plan sustainable content around audience needs", "Define audience, use cases, distribution channels, and business goals, then build topic clusters and cadence. Give every item an owner, metric, and update condition rather than a generic topic list."},
		"copy-editing":            {"Copy Editing", "Improve accuracy, structure, and readability", "Verify facts, audience, and intended action before editing structure, terminology, grammar, and redundancy. Preserve the author's voice and do not introduce unsupported claims."},
		"pricing-page-strategy":   {"Pricing Page Strategy", "Explain plans, billing, and limits clearly", "Use actual product rules to describe plan differences, billing units, quotas, overage, refunds, and intended users. Support decisions without invented discounts, scarcity, or benefit claims."},
		"onboarding-optimization": {"Onboarding Optimization", "Shorten the path from registration to first success", "Define the activation event and current funnel, then locate blocking steps, errors, and waits. Test one change at a time and measure completion, time, and retention instead of adding more helper copy."},
		"marketing-attribution":   {"Marketing Attribution", "Define explainable channel and conversion measurement", "Standardize events, windows, deduplication, and identity rules, and state the chosen attribution model. Report data gaps and privacy limits and do not present attribution as causation."},
		"product-launch":          {"Product Launch", "Coordinate scope, channels, and post-launch verification", "Define audience, date, scope, dependencies, support, and rollback. Announce only shipped behavior, then monitor adoption, failures, and feedback with an owner for every issue."},
		"customer-research":       {"Customer Research", "Understand needs from interviews and behavior", "Define the research question and sample, then ask neutral questions about specific experiences, triggers, alternatives, and outcomes. Separate quotes, observations, inference, and sample limitations."},
		"prd-writing":             {"PRD Writing", "Write product decisions as testable requirements", "Document the user problem, goals, scope, flow, rules, states, permissions, metrics, and acceptance criteria. Cite evidence, assign open questions, and never treat a mockup as the complete rule set."},
		"feature-prioritization":  {"Feature Prioritization", "Rank work by goals, evidence, and cost", "Compare user impact, strategic fit, evidence strength, cost, risk, and dependencies under one method. Show scores and assumptions and handle mandatory compliance or incident work separately."},
		"product-premortem":       {"Product Premortem", "Identify likely failure paths before execution", "Assume the project failed and find concrete causes across requirements, technology, data, operations, dependencies, and adoption. Assign owners, early signals, and mitigation to preventable high-impact risks."},
		"stakeholder-management":  {"Stakeholder Management", "Clarify influence, decision rights, and communication", "Map affected roles, goals, concerns, decision authority, and information needs. Schedule owners, materials, timing, and escalation for key decisions instead of replacing problem solving with status updates."},
		"release-notes":           {"Release Notes", "Record version changes in user-facing language", "Derive additions, fixes, changes, and required actions from final verified behavior. Use exact names and versions, exclude development history and unshipped work, and include migration steps for breaking changes."},
		"ab-test-analysis":        {"A/B Test Analysis", "Evaluate effects and uncertainty in experiments", "Verify hypothesis, randomization, sample size, duration, and metric definitions before computing effects and intervals. Check allocation, contamination, multiple comparisons, and early stopping."},
		"cohort-analysis":         {"Cohort Analysis", "Compare behavior from a shared starting event", "Define the cohort event, time grain, retention behavior, and observation window, with consistent time zones and maturity. Show sample size, curves, and segments without claiming causality from structure alone."},
		"product-strategy":        {"Product Strategy", "Connect market choice, advantage, and executable trade-offs", "Use user problems, alternatives, capabilities, constraints, and evidence to define the target market and value proposition. State what not to do, success metrics, assumptions, and ordered actions."},

		"literature-review":         {"Literature Review", "Systematically retrieve and synthesize research evidence", "Define the question, databases, keywords, period, and inclusion criteria. Record screening, compare methods and findings, and identify agreement, disagreement, bias, and evidence gaps."},
		"citation-management":       {"Citation Management", "Verify sources and keep references consistent", "Store author, title, year, identifier, and access source and verify the primary work. Generate the requested style, match in-text citations to references, and never invent missing fields."},
		"experimental-design":       {"Experimental Design", "Create testable and reproducible study plans", "Define hypotheses, variables, controls, randomization, sample size, exclusions, and analysis. Identify confounding and measurement error, predefine stopping rules, and preserve reproduction materials."},
		"scientific-peer-review":    {"Scientific Peer Review", "Assess methods, evidence, and conclusion boundaries", "Evaluate the question, methods, data, statistics, reproducibility, and conclusions separately. Cite concrete evidence and distinguish fatal flaws, fixable issues, and presentation suggestions."},
		"exploratory-data-analysis": {"Exploratory Data Analysis", "Inspect data quality, distributions, and relationships", "Confirm field meaning, collection, and sample boundaries before checking missing values, anomalies, duplicates, distributions, and group differences. Label exploratory findings as hypotheses for later testing."},
		"hypothesis-generation":     {"Scientific Hypothesis Generation", "Propose falsifiable hypotheses from evidence gaps", "Use known mechanisms, observations, and literature gaps to propose a small set of competing hypotheses. State predictions, variables, falsification conditions, and a minimal experiment for each."},
	}

	for index := range skills {
		translation, ok := translations[skills[index].ID]
		if !ok {
			continue
		}
		skills[index].NameEN = translation.name
		skills[index].DescriptionEN = translation.description
		skills[index].ContentEN = translation.content
	}
}
